package huang.river.nio;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.nio.charset.Charset;
import java.nio.charset.CharsetDecoder;
import java.nio.charset.CodingErrorAction;
import java.nio.file.FileSystems;
import java.nio.file.FileVisitResult;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.PathMatcher;
import java.nio.file.Paths;
import java.nio.file.SimpleFileVisitor;
import java.nio.file.attribute.BasicFileAttributes;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class FindFuncImpl {

	/**
	 * A {@code FileVisitor} that finds all files that match the specified pattern.
	 */
	static class Finder extends SimpleFileVisitor<Path> {

		private final PathMatcher matcher;
		private int numMatches = 0;
		
		// \\$impl
		private Pattern funcPattern = Pattern.compile(".+func.+func", Pattern.CASE_INSENSITIVE);
		
		private static final String WORD_BEGIN = "BEGIN";
		
		private static final String WORD_END = "CREATE PROCEDURE";
		
		private String funcName;
		
		private String[] funcList = {
				"SAI16.CODE_MAPPING_LIBRARY$FUNC_ANKEN_ID",
				"SAI16.CODE_MAPPING_LIBRARY$FUNC_ANKEN_ID_KOUSEI",
				"SAI16.CODE_MAPPING_LIBRARY$FUNC_EIGYOUSYO_ID",
				"SAI16.CODE_MAPPING_LIBRARY$FUNC_EIGYOUSYO_ID_KOUSIN",
				"SAI16.CODE_MAPPING_LIBRARY$FUNC_EIGYOUSYO_ID_SAISIN",
				"SAI16.CODE_MAPPING_LIBRARY$FUNC_KAKUDUKE_CODE",
				"SAI16.CODE_MAPPING_LIBRARY$FUNC_KAKUDUKE_SYORI",
				"SAI16.CODE_MAPPING_LIBRARY$FUNC_KEIYAKU_HOUHOU_KONKYO",
				"SAI16.CODE_MAPPING_LIBRARY$FUNC_KENNAI_KENGAI_SYUBETU",
				"SAI16.CODE_MAPPING_LIBRARY$FUNC_KUBUN_CODE",
				"SAI16.CODE_MAPPING_LIBRARY$FUNC_L1_CODE",
				"SAI16.CODE_MAPPING_LIBRARY$FUNC_L2_CODE",
				"SAI16.CODE_MAPPING_LIBRARY$FUNC_L3_CODE",
				"SAI16.CODE_MAPPING_LIBRARY$FUNC_NAIBU_KASYO_ID",
				"SAI16.CODE_MAPPING_LIBRARY$FUNC_NAIBU_ZIGYOU_ID",
				"SAI16.CODE_MAPPING_LIBRARY$FUNC_SIKAKU_CODE",
				"SAI16.CODE_MAPPING_LIBRARY$FUNC_TIIKI_CODE",
				"SAI16.CODE_MAPPING_LIBRARY$FUNC_TODOUHUKEN_CODE",
				"SAI16.COMMON_LIBRARY$CHECK_EIGYOUSYO_KOUSIN_RIREKI",
				"SAI16.COMMON_LIBRARY$CHECK_EIGYOUSYO_SAISIN_RIREKI",
				"SAI16.COMMON_LIBRARY$CHECK_GYOUSYA_KOUSIN_RIREKI",
				"SAI16.COMMON_LIBRARY$CHECK_GYOUSYA_SAISIN_RIREKI",
				"SAI16.COMMON_LIBRARY$CHECK_HENKOU_IPPAN",
				"SAI16.COMMON_LIBRARY$CHECK_HENKOU_JV",
				"SAI16.COMMON_LIBRARY$FUNC_IKOU_KIBOU_FLAG",
				"SAI16.COMMON_LIBRARY$FUNC_KASYO_CODE",
				"SAI16.COMMON_LIBRARY$FUNC_NENDO",
				"SAI16.COMMON_LIBRARY$FUNC_SAISIN_ANKEN_RIREKI_NO",
				"SAI16.COMMON_LIBRARY$FUNC_SAISIN_EIGYOU_RIREKI_NO",
				"SAI16.COMMON_LIBRARY$FUNC_SAISIN_GYOUSYA_RIREKI_NO",
				"SAI16.COMMON_LIBRARY$FUNC_SAISIN_TORIKESI_FLAG",
				"SAI16.COMMON_LIBRARY$FUNC_TANTOU_KASYO_ID",
				"SAI16.COMMON_LIBRARY$FUNC_TO_DATE",
				"SAI16.COMMON_LIBRARY$FUNC_TO_NUMBER",
				"SAI16.COMMON_LIBRARY$FUNC_TUUTI_BUNSYO_RYA_HANI",
				"SAI16.COMMON_LIBRARY$FUNC_WAREKI_MEIBO_MEI",
				"SAI16.COMMON_LIBRARY$GET_ANKEN_RIREKI_SAKUSEI_FLAG",
				"SAI16.COMMON_LIBRARY$REPLACE_KASYO_CODE",
				"SAI16.CREATE_SUMMARY_DATA$FUNC_GET_TOUSYO_NENDOWARIGAKU",
				"SAI16.EXECUTE_DATA_IKOU$FUNC_IS_IKOU_TAISYOU",
				"SAI16.EXISTS_DATA_RECORD$FUNC_ANKEN_NYUUSATU_ANKEN",
				"SAI16.EXISTS_DATA_RECORD$FUNC_ANKEN_SIKKOU",
				"SAI16.EXISTS_DATA_RECORD$FUNC_ANKEN_SIKKOU_KAMOKU",
				"SAI16.EXISTS_DATA_RECORD$FUNC_ANKEN_SISYUTU_HUTAN",
				"SAI16.EXISTS_DATA_RECORD$FUNC_ANKEN_SISYUTU_HUTA_KAMO",
				"SAI16.EXISTS_DATA_RECORD$FUNC_ANKEN_SISYUTU_HUTA_SAI",
				"SAI16.EXISTS_DATA_RECORD$FUNC_NYUUSATU_ANKEN",
				"SAI16.EXISTS_DATA_RECORD$FUNC_NYUUSATU_ANKEN_KOUZI_NULL",
				"SAI16.EXISTS_DATA_RECORD$FUNC_SIKKOU",
				"SAI16.EXISTS_DATA_RECORD$FUNC_SIKKOU_KAMOKU",
				"SAI16.EXISTS_DATA_RECORD$FUNC_SISYUTU_HUTAN",
				"SAI16.EXISTS_DATA_RECORD$FUNC_SISYUTU_HUTAN_KAMOKU",
				"SAI16.EXISTS_DATA_RECORD$FUNC_SISYUTU_HUTAN_SAIKENSYA",
				"SAI16.EXISTS_DATA_RECORD$FUNC_SISYUTU_HUTAN_SAI_KAMO",
				"SAI16.EXISTS_DATA_RECORD2$FUNC_DOBOKU_KOBETU",
				"SAI16.EXISTS_DATA_RECORD2$FUNC_DOBOKU_KYOUTUU",
				"SAI16.EXISTS_DATA_RECORD2$FUNC_EIGYOU_DOBOKU_KOBETU",
				"SAI16.EXISTS_DATA_RECORD2$FUNC_EIGYOU_DOBOKU_KYOUTUU",
				"SAI16.EXISTS_DATA_RECORD2$FUNC_EIGYOU_KEN_KOBETU_KOU",
				"SAI16.EXISTS_DATA_RECORD2$FUNC_EIGYOU_KEN_KOBETU_ZEN",
				"SAI16.EXISTS_DATA_RECORD2$FUNC_EIGYOU_KEN_KYOU_KOU",
				"SAI16.EXISTS_DATA_RECORD2$FUNC_EIGYOU_KEN_KYOU_ZEN",
				"SAI16.EXISTS_DATA_RECORD2$FUNC_EIGYOU_KIHON_KOBETU",
				"SAI16.EXISTS_DATA_RECORD2$FUNC_EIGYOU_KIHON_KYOUTUU",
				"SAI16.EXISTS_DATA_RECORD2$FUNC_EIGYOU_SEKKEI_KOBETU",
				"SAI16.EXISTS_DATA_RECORD2$FUNC_EIGYOU_SEKKEI_KYOU_KOU",
				"SAI16.EXISTS_DATA_RECORD2$FUNC_EIGYOU_SEKKEI_KYOU_ZEN",
				"SAI16.EXISTS_DATA_RECORD2$FUNC_KEN_KOBETU_KOU",
				"SAI16.EXISTS_DATA_RECORD2$FUNC_KEN_KOBETU_ZEN",
				"SAI16.EXISTS_DATA_RECORD2$FUNC_KEN_KYOU_KOU",
				"SAI16.EXISTS_DATA_RECORD2$FUNC_KEN_KYOU_ZEN",
				"SAI16.EXISTS_DATA_RECORD2$FUNC_KIHON_KOBETU",
				"SAI16.EXISTS_DATA_RECORD2$FUNC_KIHON_KYOUTUU",
				"SAI16.EXISTS_DATA_RECORD2$FUNC_SEKKEI_KOBETU",
				"SAI16.EXISTS_DATA_RECORD2$FUNC_SEKKEI_KYOU_KOU",
				"SAI16.EXISTS_DATA_RECORD2$FUNC_SEKKEI_KYOU_ZEN",
				"SAI16.GET_BODY_ID$FUNC_DOBOKU_KOBETU",
				"SAI16.GET_BODY_ID$FUNC_DOBOKU_KYOUTUU",
				"SAI16.GET_BODY_ID$FUNC_KENSETU_KOBETU_KOUHAN",
				"SAI16.GET_BODY_ID$FUNC_KENSETU_KOBETU_ZENHAN",
				"SAI16.GET_BODY_ID$FUNC_KENSETU_KYOUTUU_KOUHAN",
				"SAI16.GET_BODY_ID$FUNC_KENSETU_KYOUTUU_ZENHAN",
				"SAI16.GET_BODY_ID$FUNC_KIHON_KOBETU",
				"SAI16.GET_BODY_ID$FUNC_KIHON_KYOUTUU",
				"SAI16.GET_BODY_ID$FUNC_NYUUSATU_ANKEN",
				"SAI16.GET_BODY_ID$FUNC_NYUUSATU_SANKA_GYOUSYA",
				"SAI16.GET_BODY_ID$FUNC_SEISEKI_HYOUTEI",
				"SAI16.GET_BODY_ID$FUNC_SEKKEI_KOBETU",
				"SAI16.GET_BODY_ID$FUNC_SEKKEI_KYOUTUU_KOUHAN",
				"SAI16.GET_BODY_ID$FUNC_SEKKEI_KYOUTUU_ZENHAN",
				"SAI16.GET_BODY_ID$FUNC_SIKKOU",
				"SAI16.GET_BODY_ID$FUNC_SIKKOU_KAMOKU",
				"SAI16.GET_BODY_ID$FUNC_SISYUTU_HUTAN",
				"SAI16.GET_BODY_ID$FUNC_SISYUTU_HUTAN_KAMOKU",
				"SAI16.GET_BODY_ID$FUNC_SISYUTU_HUTAN_NENDOWARI",
				"SAI16.GET_BODY_ID$FUNC_SISYUTU_HUTAN_SAIKENSYA",
				"SAI16.GET_DATA_ZYOUTAI_FOR_UPDATE$FUNC_ANKEN",
				"SAI16.GET_DATA_ZYOUTAI_FOR_UPDATE$FUNC_DOBOKU_KOBETU",
				"SAI16.GET_DATA_ZYOUTAI_FOR_UPDATE$FUNC_DOBOKU_KYOUTUU",
				"SAI16.GET_DATA_ZYOUTAI_FOR_UPDATE$FUNC_EIGYOUSYO",
				"SAI16.GET_DATA_ZYOUTAI_FOR_UPDATE$FUNC_KENSETU_KOBETU_KOUHAN",
				"SAI16.GET_DATA_ZYOUTAI_FOR_UPDATE$FUNC_KENSETU_KOBETU_ZENHAN",
				"SAI16.GET_DATA_ZYOUTAI_FOR_UPDATE$FUNC_KENSETU_KYOUTUU_KOUHAN",
				"SAI16.GET_DATA_ZYOUTAI_FOR_UPDATE$FUNC_KENSETU_KYOUTUU_ZENHAN",
				"SAI16.GET_DATA_ZYOUTAI_FOR_UPDATE$FUNC_KIHON_KOBETU",
				"SAI16.GET_DATA_ZYOUTAI_FOR_UPDATE$FUNC_KIHON_KYOUTUU",
				"SAI16.GET_DATA_ZYOUTAI_FOR_UPDATE$FUNC_NYUUSATU_ANKEN",
				"SAI16.GET_DATA_ZYOUTAI_FOR_UPDATE$FUNC_NYUUSATU_SANKA_GYOUSYA",
				"SAI16.GET_DATA_ZYOUTAI_FOR_UPDATE$FUNC_SEISEKI_HYOUTEI",
				"SAI16.GET_DATA_ZYOUTAI_FOR_UPDATE$FUNC_SEKKEI_KOBETU",
				"SAI16.GET_DATA_ZYOUTAI_FOR_UPDATE$FUNC_SEKKEI_KYOUTUU_KOUHAN",
				"SAI16.GET_DATA_ZYOUTAI_FOR_UPDATE$FUNC_SEKKEI_KYOUTUU_ZENHAN",
				"SAI16.GET_DATA_ZYOUTAI_FOR_UPDATE$FUNC_SIKKOU",
				"SAI16.GET_DATA_ZYOUTAI_FOR_UPDATE$FUNC_SIKKOU_KAMOKU",
				"SAI16.GET_DATA_ZYOUTAI_FOR_UPDATE$FUNC_SISYUTU_HUTAN",
				"SAI16.GET_DATA_ZYOUTAI_FOR_UPDATE$FUNC_SISYUTU_HUTAN_KAMOKU",
				"SAI16.GET_DATA_ZYOUTAI_FOR_UPDATE$FUNC_SISYUTU_HUTAN_NENDOWARI",
				"SAI16.GET_DATA_ZYOUTAI_FOR_UPDATE$FUNC_SISYUTU_HUTAN_SAIKENSYA",
				"SAI16.MANAGE_ANKEN$FUNC_ANKEN_YUUKOU_FLAG",
				"SAI16.MANAGE_ANKEN$FUNC_CHECK_SISYUTU_RIYUU",
				"SAI16.MANAGE_ANKEN$FUNC_CHECK_SYORI_TAISYOU_KOUZI",
				"SAI16.MANAGE_ANKEN$FUNC_CHECK_TORIKESI",
				"SAI16.MANAGE_GYOUSYA$FUNC_GET_SYUUKEI_ZYOUTAI",
				"SAI16.RULE_CHECK_LIBRARY$CHECK_ANKEN_CHECK_KAIHI",
				"SAI16.RULE_CHECK_LIBRARY$FUNC_20207",
				"SAI16.RULE_CHECK_LIBRARY$FUNC_20305",
				"SAI16.RULE_CHECK_LIBRARY$FUNC_20403",
				"SAI16.RULE_CHECK_LIBRARY$FUNC_20404",
				"SAI16.RULE_CHECK_LIBRARY$FUNC_20405",
				"SAI16.RULE_CHECK_LIBRARY$FUNC_20406",
				"SAI16.RULE_CHECK_LIBRARY$FUNC_20407",
				"SAI16.RULE_CHECK_LIBRARY$FUNC_20408",
				"SAI16.RULE_CHECK_LIBRARY$FUNC_20409",
				"SAI16.RULE_CHECK_LIBRARY$FUNC_20410",
				"SAI16.RULE_CHECK_LIBRARY$FUNC_20411",
				"SAI16.RULE_CHECK_LIBRARY$FUNC_20412",
				"SAI16.RULE_CHECK_LIBRARY$FUNC_20413",
				"SAI16.RULE_CHECK_LIBRARY$FUNC_20415",
				"SAI16.RULE_CHECK_LIBRARY$FUNC_20416",
				"SAI16.RULE_CHECK_LIBRARY$FUNC_20417",
				"SAI16.RULE_CHECK_LIBRARY$FUNC_20418",
				"SAI16.RULE_CHECK_LIBRARY$FUNC_20419",
				"SAI16.RULE_CHECK_LIBRARY$FUNC_20420",
				"SAI16.RULE_CHECK_LIBRARY$FUNC_KANSEI_BI",	
		};
		
		private String funcListStr = "SAI16.CODE_MAPPING_LIBRARY$FUNC_ANKEN_ID\r\n"
				+ "SAI16.CODE_MAPPING_LIBRARY$FUNC_ANKEN_ID_KOUSEI\r\n"
				+ "SAI16.CODE_MAPPING_LIBRARY$FUNC_EIGYOUSYO_ID\r\n"
				+ "SAI16.CODE_MAPPING_LIBRARY$FUNC_EIGYOUSYO_ID_KOUSIN\r\n"
				+ "SAI16.CODE_MAPPING_LIBRARY$FUNC_EIGYOUSYO_ID_SAISIN\r\n"
				+ "SAI16.CODE_MAPPING_LIBRARY$FUNC_KAKUDUKE_CODE\r\n"
				+ "SAI16.CODE_MAPPING_LIBRARY$FUNC_KAKUDUKE_SYORI\r\n"
				+ "SAI16.CODE_MAPPING_LIBRARY$FUNC_KEIYAKU_HOUHOU_KONKYO\r\n"
				+ "SAI16.CODE_MAPPING_LIBRARY$FUNC_KENNAI_KENGAI_SYUBETU\r\n"
				+ "SAI16.CODE_MAPPING_LIBRARY$FUNC_KUBUN_CODE\r\n"
				+ "SAI16.CODE_MAPPING_LIBRARY$FUNC_L1_CODE\r\n"
				+ "SAI16.CODE_MAPPING_LIBRARY$FUNC_L2_CODE\r\n"
				+ "SAI16.CODE_MAPPING_LIBRARY$FUNC_L3_CODE\r\n"
				+ "SAI16.CODE_MAPPING_LIBRARY$FUNC_NAIBU_KASYO_ID\r\n"
				+ "SAI16.CODE_MAPPING_LIBRARY$FUNC_NAIBU_ZIGYOU_ID\r\n"
				+ "SAI16.CODE_MAPPING_LIBRARY$FUNC_SIKAKU_CODE\r\n"
				+ "SAI16.CODE_MAPPING_LIBRARY$FUNC_TIIKI_CODE\r\n"
				+ "SAI16.CODE_MAPPING_LIBRARY$FUNC_TODOUHUKEN_CODE\r\n"
				+ "SAI16.COMMON_LIBRARY$CHECK_EIGYOUSYO_KOUSIN_RIREKI\r\n"
				+ "SAI16.COMMON_LIBRARY$CHECK_EIGYOUSYO_SAISIN_RIREKI\r\n"
				+ "SAI16.COMMON_LIBRARY$CHECK_GYOUSYA_KOUSIN_RIREKI\r\n"
				+ "SAI16.COMMON_LIBRARY$CHECK_GYOUSYA_SAISIN_RIREKI\r\n"
				+ "SAI16.COMMON_LIBRARY$CHECK_HENKOU_IPPAN\r\n"
				+ "SAI16.COMMON_LIBRARY$CHECK_HENKOU_JV\r\n"
				+ "SAI16.COMMON_LIBRARY$FUNC_IKOU_KIBOU_FLAG\r\n"
				+ "SAI16.COMMON_LIBRARY$FUNC_KASYO_CODE\r\n"
				+ "SAI16.COMMON_LIBRARY$FUNC_NENDO\r\n"
				+ "SAI16.COMMON_LIBRARY$FUNC_SAISIN_ANKEN_RIREKI_NO\r\n"
				+ "SAI16.COMMON_LIBRARY$FUNC_SAISIN_EIGYOU_RIREKI_NO\r\n"
				+ "SAI16.COMMON_LIBRARY$FUNC_SAISIN_GYOUSYA_RIREKI_NO\r\n"
				+ "SAI16.COMMON_LIBRARY$FUNC_SAISIN_TORIKESI_FLAG\r\n"
				+ "SAI16.COMMON_LIBRARY$FUNC_TANTOU_KASYO_ID\r\n"
				+ "SAI16.COMMON_LIBRARY$FUNC_TO_DATE\r\n"
				+ "SAI16.COMMON_LIBRARY$FUNC_TO_NUMBER\r\n"
				+ "SAI16.COMMON_LIBRARY$FUNC_TUUTI_BUNSYO_RYA_HANI\r\n"
				+ "SAI16.COMMON_LIBRARY$FUNC_WAREKI_MEIBO_MEI\r\n"
				+ "SAI16.COMMON_LIBRARY$GET_ANKEN_RIREKI_SAKUSEI_FLAG\r\n"
				+ "SAI16.COMMON_LIBRARY$REPLACE_KASYO_CODE\r\n"
				+ "SAI16.CREATE_SUMMARY_DATA$FUNC_GET_TOUSYO_NENDOWARIGAKU\r\n"
				+ "SAI16.EXECUTE_DATA_IKOU$FUNC_IS_IKOU_TAISYOU\r\n"
				+ "SAI16.EXISTS_DATA_RECORD$FUNC_ANKEN_NYUUSATU_ANKEN\r\n"
				+ "SAI16.EXISTS_DATA_RECORD$FUNC_ANKEN_SIKKOU\r\n"
				+ "SAI16.EXISTS_DATA_RECORD$FUNC_ANKEN_SIKKOU_KAMOKU\r\n"
				+ "SAI16.EXISTS_DATA_RECORD$FUNC_ANKEN_SISYUTU_HUTAN\r\n"
				+ "SAI16.EXISTS_DATA_RECORD$FUNC_ANKEN_SISYUTU_HUTA_KAMO\r\n"
				+ "SAI16.EXISTS_DATA_RECORD$FUNC_ANKEN_SISYUTU_HUTA_SAI\r\n"
				+ "SAI16.EXISTS_DATA_RECORD$FUNC_NYUUSATU_ANKEN\r\n"
				+ "SAI16.EXISTS_DATA_RECORD$FUNC_NYUUSATU_ANKEN_KOUZI_NULL\r\n"
				+ "SAI16.EXISTS_DATA_RECORD$FUNC_SIKKOU\r\n"
				+ "SAI16.EXISTS_DATA_RECORD$FUNC_SIKKOU_KAMOKU\r\n"
				+ "SAI16.EXISTS_DATA_RECORD$FUNC_SISYUTU_HUTAN\r\n"
				+ "SAI16.EXISTS_DATA_RECORD$FUNC_SISYUTU_HUTAN_KAMOKU\r\n"
				+ "SAI16.EXISTS_DATA_RECORD$FUNC_SISYUTU_HUTAN_SAIKENSYA\r\n"
				+ "SAI16.EXISTS_DATA_RECORD$FUNC_SISYUTU_HUTAN_SAI_KAMO\r\n"
				+ "SAI16.EXISTS_DATA_RECORD2$FUNC_DOBOKU_KOBETU\r\n"
				+ "SAI16.EXISTS_DATA_RECORD2$FUNC_DOBOKU_KYOUTUU\r\n"
				+ "SAI16.EXISTS_DATA_RECORD2$FUNC_EIGYOU_DOBOKU_KOBETU\r\n"
				+ "SAI16.EXISTS_DATA_RECORD2$FUNC_EIGYOU_DOBOKU_KYOUTUU\r\n"
				+ "SAI16.EXISTS_DATA_RECORD2$FUNC_EIGYOU_KEN_KOBETU_KOU\r\n"
				+ "SAI16.EXISTS_DATA_RECORD2$FUNC_EIGYOU_KEN_KOBETU_ZEN\r\n"
				+ "SAI16.EXISTS_DATA_RECORD2$FUNC_EIGYOU_KEN_KYOU_KOU\r\n"
				+ "SAI16.EXISTS_DATA_RECORD2$FUNC_EIGYOU_KEN_KYOU_ZEN\r\n"
				+ "SAI16.EXISTS_DATA_RECORD2$FUNC_EIGYOU_KIHON_KOBETU\r\n"
				+ "SAI16.EXISTS_DATA_RECORD2$FUNC_EIGYOU_KIHON_KYOUTUU\r\n"
				+ "SAI16.EXISTS_DATA_RECORD2$FUNC_EIGYOU_SEKKEI_KOBETU\r\n"
				+ "SAI16.EXISTS_DATA_RECORD2$FUNC_EIGYOU_SEKKEI_KYOU_KOU\r\n"
				+ "SAI16.EXISTS_DATA_RECORD2$FUNC_EIGYOU_SEKKEI_KYOU_ZEN\r\n"
				+ "SAI16.EXISTS_DATA_RECORD2$FUNC_KEN_KOBETU_KOU\r\n"
				+ "SAI16.EXISTS_DATA_RECORD2$FUNC_KEN_KOBETU_ZEN\r\n"
				+ "SAI16.EXISTS_DATA_RECORD2$FUNC_KEN_KYOU_KOU\r\n"
				+ "SAI16.EXISTS_DATA_RECORD2$FUNC_KEN_KYOU_ZEN\r\n"
				+ "SAI16.EXISTS_DATA_RECORD2$FUNC_KIHON_KOBETU\r\n"
				+ "SAI16.EXISTS_DATA_RECORD2$FUNC_KIHON_KYOUTUU\r\n"
				+ "SAI16.EXISTS_DATA_RECORD2$FUNC_SEKKEI_KOBETU\r\n"
				+ "SAI16.EXISTS_DATA_RECORD2$FUNC_SEKKEI_KYOU_KOU\r\n"
				+ "SAI16.EXISTS_DATA_RECORD2$FUNC_SEKKEI_KYOU_ZEN\r\n"
				+ "SAI16.GET_BODY_ID$FUNC_DOBOKU_KOBETU\r\n"
				+ "SAI16.GET_BODY_ID$FUNC_DOBOKU_KYOUTUU\r\n"
				+ "SAI16.GET_BODY_ID$FUNC_KENSETU_KOBETU_KOUHAN\r\n"
				+ "SAI16.GET_BODY_ID$FUNC_KENSETU_KOBETU_ZENHAN\r\n"
				+ "SAI16.GET_BODY_ID$FUNC_KENSETU_KYOUTUU_KOUHAN\r\n"
				+ "SAI16.GET_BODY_ID$FUNC_KENSETU_KYOUTUU_ZENHAN\r\n"
				+ "SAI16.GET_BODY_ID$FUNC_KIHON_KOBETU\r\n"
				+ "SAI16.GET_BODY_ID$FUNC_KIHON_KYOUTUU\r\n"
				+ "SAI16.GET_BODY_ID$FUNC_NYUUSATU_ANKEN\r\n"
				+ "SAI16.GET_BODY_ID$FUNC_NYUUSATU_SANKA_GYOUSYA\r\n"
				+ "SAI16.GET_BODY_ID$FUNC_SEISEKI_HYOUTEI\r\n"
				+ "SAI16.GET_BODY_ID$FUNC_SEKKEI_KOBETU\r\n"
				+ "SAI16.GET_BODY_ID$FUNC_SEKKEI_KYOUTUU_KOUHAN\r\n"
				+ "SAI16.GET_BODY_ID$FUNC_SEKKEI_KYOUTUU_ZENHAN\r\n"
				+ "SAI16.GET_BODY_ID$FUNC_SIKKOU\r\n"
				+ "SAI16.GET_BODY_ID$FUNC_SIKKOU_KAMOKU\r\n"
				+ "SAI16.GET_BODY_ID$FUNC_SISYUTU_HUTAN\r\n"
				+ "SAI16.GET_BODY_ID$FUNC_SISYUTU_HUTAN_KAMOKU\r\n"
				+ "SAI16.GET_BODY_ID$FUNC_SISYUTU_HUTAN_NENDOWARI\r\n"
				+ "SAI16.GET_BODY_ID$FUNC_SISYUTU_HUTAN_SAIKENSYA\r\n"
				+ "SAI16.GET_DATA_ZYOUTAI_FOR_UPDATE$FUNC_ANKEN\r\n"
				+ "SAI16.GET_DATA_ZYOUTAI_FOR_UPDATE$FUNC_DOBOKU_KOBETU\r\n"
				+ "SAI16.GET_DATA_ZYOUTAI_FOR_UPDATE$FUNC_DOBOKU_KYOUTUU\r\n"
				+ "SAI16.GET_DATA_ZYOUTAI_FOR_UPDATE$FUNC_EIGYOUSYO\r\n"
				+ "SAI16.GET_DATA_ZYOUTAI_FOR_UPDATE$FUNC_KENSETU_KOBETU_KOUHAN\r\n"
				+ "SAI16.GET_DATA_ZYOUTAI_FOR_UPDATE$FUNC_KENSETU_KOBETU_ZENHAN\r\n"
				+ "SAI16.GET_DATA_ZYOUTAI_FOR_UPDATE$FUNC_KENSETU_KYOUTUU_KOUHAN\r\n"
				+ "SAI16.GET_DATA_ZYOUTAI_FOR_UPDATE$FUNC_KENSETU_KYOUTUU_ZENHAN\r\n"
				+ "SAI16.GET_DATA_ZYOUTAI_FOR_UPDATE$FUNC_KIHON_KOBETU\r\n"
				+ "SAI16.GET_DATA_ZYOUTAI_FOR_UPDATE$FUNC_KIHON_KYOUTUU\r\n"
				+ "SAI16.GET_DATA_ZYOUTAI_FOR_UPDATE$FUNC_NYUUSATU_ANKEN\r\n"
				+ "SAI16.GET_DATA_ZYOUTAI_FOR_UPDATE$FUNC_NYUUSATU_SANKA_GYOUSYA\r\n"
				+ "SAI16.GET_DATA_ZYOUTAI_FOR_UPDATE$FUNC_SEISEKI_HYOUTEI\r\n"
				+ "SAI16.GET_DATA_ZYOUTAI_FOR_UPDATE$FUNC_SEKKEI_KOBETU\r\n"
				+ "SAI16.GET_DATA_ZYOUTAI_FOR_UPDATE$FUNC_SEKKEI_KYOUTUU_KOUHAN\r\n"
				+ "SAI16.GET_DATA_ZYOUTAI_FOR_UPDATE$FUNC_SEKKEI_KYOUTUU_ZENHAN\r\n"
				+ "SAI16.GET_DATA_ZYOUTAI_FOR_UPDATE$FUNC_SIKKOU\r\n"
				+ "SAI16.GET_DATA_ZYOUTAI_FOR_UPDATE$FUNC_SIKKOU_KAMOKU\r\n"
				+ "SAI16.GET_DATA_ZYOUTAI_FOR_UPDATE$FUNC_SISYUTU_HUTAN\r\n"
				+ "SAI16.GET_DATA_ZYOUTAI_FOR_UPDATE$FUNC_SISYUTU_HUTAN_KAMOKU\r\n"
				+ "SAI16.GET_DATA_ZYOUTAI_FOR_UPDATE$FUNC_SISYUTU_HUTAN_NENDOWARI\r\n"
				+ "SAI16.GET_DATA_ZYOUTAI_FOR_UPDATE$FUNC_SISYUTU_HUTAN_SAIKENSYA\r\n"
				+ "SAI16.MANAGE_ANKEN$FUNC_ANKEN_YUUKOU_FLAG\r\n"
				+ "SAI16.MANAGE_ANKEN$FUNC_CHECK_SISYUTU_RIYUU\r\n"
				+ "SAI16.MANAGE_ANKEN$FUNC_CHECK_SYORI_TAISYOU_KOUZI\r\n"
				+ "SAI16.MANAGE_ANKEN$FUNC_CHECK_TORIKESI\r\n"
				+ "SAI16.MANAGE_GYOUSYA$FUNC_GET_SYUUKEI_ZYOUTAI\r\n"
				+ "SAI16.RULE_CHECK_LIBRARY$CHECK_ANKEN_CHECK_KAIHI\r\n"
				+ "SAI16.RULE_CHECK_LIBRARY$FUNC_20207\r\n"
				+ "SAI16.RULE_CHECK_LIBRARY$FUNC_20305\r\n"
				+ "SAI16.RULE_CHECK_LIBRARY$FUNC_20403\r\n"
				+ "SAI16.RULE_CHECK_LIBRARY$FUNC_20404\r\n"
				+ "SAI16.RULE_CHECK_LIBRARY$FUNC_20405\r\n"
				+ "SAI16.RULE_CHECK_LIBRARY$FUNC_20406\r\n"
				+ "SAI16.RULE_CHECK_LIBRARY$FUNC_20407\r\n"
				+ "SAI16.RULE_CHECK_LIBRARY$FUNC_20408\r\n"
				+ "SAI16.RULE_CHECK_LIBRARY$FUNC_20409\r\n"
				+ "SAI16.RULE_CHECK_LIBRARY$FUNC_20410\r\n"
				+ "SAI16.RULE_CHECK_LIBRARY$FUNC_20411\r\n"
				+ "SAI16.RULE_CHECK_LIBRARY$FUNC_20412\r\n"
				+ "SAI16.RULE_CHECK_LIBRARY$FUNC_20413\r\n"
				+ "SAI16.RULE_CHECK_LIBRARY$FUNC_20415\r\n"
				+ "SAI16.RULE_CHECK_LIBRARY$FUNC_20416\r\n"
				+ "SAI16.RULE_CHECK_LIBRARY$FUNC_20417\r\n"
				+ "SAI16.RULE_CHECK_LIBRARY$FUNC_20418\r\n"
				+ "SAI16.RULE_CHECK_LIBRARY$FUNC_20419\r\n"
				+ "SAI16.RULE_CHECK_LIBRARY$FUNC_20420\r\n"
				+ "SAI16.RULE_CHECK_LIBRARY$FUNC_KANSEI_BI";
		
		private int findFunc = -1;
		private int findBegin = -1;
		private int findeEnd = -1;
		
		private StringBuffer sb = new StringBuffer();
		
		private List<String> rstList = new ArrayList<String>();
		
		private int matchCount = 0;

		public Finder(String pattern) {
			matcher = FileSystems.getDefault().getPathMatcher("glob:" + pattern);
		}
		
		public Finder(String pattern, String funcName) {
			matcher = FileSystems.getDefault().getPathMatcher("glob:" + pattern);
			this.funcName = funcName;
		}

		// Compares the glob pattern against
		// the file or directory name.
		void find(Path file) throws IOException {
			Path name = file.getFileName();
			if (name != null && matcher.matches(name)) {
				numMatches++;
//				System.out.println(file.getFileName());
			
				processFile(file);
				
				
			}
		}
		
		void processFile(Path file)  {
			
			
			
			// file all line
			List<String> lineList;
			String line = null;
			int i = 0;
			try {
				
//				Charset.forName("shift-jis").newDecoder();
				 CharsetDecoder decoder = Charset.forName("windows-31j").newDecoder();
			     decoder.onMalformedInput(CodingErrorAction.REPORT);
			     clearFind();
				this.rstList.add(file.getFileName().toString());
				BufferedReader br = new BufferedReader(new InputStreamReader(
						new FileInputStream(new File(file.toString())), 
						decoder ));
				while((line = br.readLine()) != null) {
					findCallFunc(line, i);
					 if(this.findeEnd>=0) {
						 clearFind();
						 return;
					 }
					 i++;
				}
				
				clearFind();
				
			} catch (IOException e) {
				System.out.println(file.getFileName());
				System.out.println(String.format("%d:%s", i , line));
				e.printStackTrace();
			}
			
			
		}
		
		void findCallFunc(String line, int lineNo) {	
			String lineUpper = line.toUpperCase();
			StringBuffer sb = new StringBuffer();
			if(isFindFunc(lineUpper)) {
				
				
				if(lineUpper.indexOf("IF")>=0) {
					return;
				}
				
				Matcher m = this.funcPattern.matcher(lineUpper);
				if(m.find()) {
					return;
				}
				
				sb.append("line:");
				sb.append(String.valueOf(lineNo));
				sb.append(",");
				sb.append(line);
//				sb.append("\r\n");
				this.rstList.add(sb.toString());
				sb.setLength(0);
//				
//				if(lineUpper.indexOf("SET")>=0) {
//					sb.append(",");
//					sb.append("set");
//				}
//				
				
				
			
				
				
			}
			
			
		}
		
		boolean isFindFunc(String str) {
			for(int i=0;i<this.funcList.length;i++) {
				if(str.indexOf(funcList[i])>=0) {
					return true;
				}
			}
			return false;
		}
			
		void processLine(String line, int lineNo) {	
			
			Matcher macher = funcPattern.matcher(line);
			
			if(macher.find()) {
				
				String lineUpper = line.toUpperCase();
				int idx = lineUpper.indexOf("CREATE");
				if(idx>=0) {
					return ;
				}
				idx = lineUpper.indexOf("DROP");
				if(idx>=0) {
					return ;
				}
				
				idx = lineUpper.indexOf("EXECUTE");
				if(idx>=0) {
					return ;
				}
				
				this.findFunc = 1;
				this.rstList.add(String.format("line:%d,%s", lineNo, line));
				return;
			}
			
		}
		
		void clearFind() {
			this.findBegin = -1;
			this.findeEnd = -1;
			this.findFunc = -1;
//			this.rstList.clear();
//			sb.setLength(0);
		}

		// Prints the total number of
		// matches to standard out.
		void done() {
//			System.out.println("Matched: " + numMatches);
			for(String str : rstList) {
				System.out.println(str);
			}
			System.out.println(matchCount);
		}

		// Invoke the pattern matching
		// method on each file.
		@Override
		public FileVisitResult visitFile(Path file, BasicFileAttributes attrs) throws IOException {
			find(file);
			return FileVisitResult.CONTINUE;
		}

		// Invoke the pattern matching
		// method on each directory.
		@Override
		public FileVisitResult preVisitDirectory(Path dir, BasicFileAttributes attrs) throws IOException {
			find(dir);
			return FileVisitResult.CONTINUE;
		}

		@Override
		public FileVisitResult visitFileFailed(Path file, IOException exc) {
			System.err.println(exc);
			return FileVisitResult.CONTINUE;
		}
	}

	static void usage() {
		System.err.println("java Find <path>" + " -name \"<glob_pattern>\"");
		System.exit(-1);
	}

	public void process(String filePath, String namep) throws IOException {

		Path startingDir = Paths.get(filePath);
		String pattern = namep;
//        for(int i=0;i<funcList.length;i++) {
//        	Finder finder = new Finder(pattern,funcList[i]);
//    		Files.walkFileTree(startingDir, finder);
//    		finder.done();
//        }
		
        Finder finder = new Finder(pattern);
		Files.walkFileTree(startingDir, finder);
		finder.done();
	}
}